DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS state CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS shopping_cart CASCADE;
DROP TABLE IF EXISTS products_in_cart CASCADE;